<?php

/**
 * @file
 *   Bypass Drupal Core page caching based on specific user-agent strings.
 */

/**
 * Implements hook_boot().
 */
function ua_cache_bypass_boot() {
  // Check if user is annonymous, caching is enabled, and user-agent matches.
  $agents = variable_get('ua_cache_bypass_crawler_names', array('MyUserAgent/1.0'));
  $cache = variable_get('cache', CACHE_DISABLED);
  global $user;

  if ($user->uid == 0 && $cache == CACHE_NORMAL && in_array($_SERVER['HTTP_USER_AGENT'], $agents)) {
    // This ob_start() line is important for generating a cache at the end.
    ob_start();

    // Circumvent page cache (borrowed from bootstrap.inc + index.php).
    drupal_page_header();
    drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

    // Log the bypass if appropriate.
    ua_cache_bypass_log_bypass();

    $return = menu_execute_active_handler();
    if (is_int($return)) {
      switch ($return) {
        case MENU_NOT_FOUND:
          drupal_not_found();
          break;
        case MENU_ACCESS_DENIED:
          drupal_access_denied();
          break;
        case MENU_SITE_OFFLINE:
          drupal_site_offline();
          break;
      }
    }
    elseif (isset($return)) {
      print theme('page', $return);
    }

    drupal_page_footer();

    exit;
  }
}


/**
 * Implements hook_help().
 */
function ua_cache_bypass_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ua_cache_bypass':
      return filter_filter('process', 1, NULL, file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}


/**
 * Implements hook_perm().
 */
function ua_cache_bypass_perm() {
  return array('administer ua cache bypass');
}


/**
 * Implements hook_menu().
 */
function ua_cache_bypass_menu() {
  $items = array();
  $items['admin/settings/ua_cache_bypass'] = array(
    'title' => 'User-Agent Cache Bypass',
    'description' => 'Configuration for Tableau Crawl Bypass.',
    'access callback' => 'user_access',
    'access arguments' => array('administer ua cache bypass'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ua_cache_bypass_settings'),
    'file' => 'ua_cache_bypass.admin.inc',
  );

  return $items;
}


/**
 * Helper function to log occurences.
 */
function ua_cache_bypass_log_bypass() {
  // Get some variables.
  $time = time();
  $last_record_time = variable_get('ua_cache_bypass_last_log', time());
  $log_interval = variable_get('ua_cache_bypass_log_interval', 86400);

  // If appropriate, log via watchdog.
  if ($log_interval && $time - $last_record_time >= $log_interval) {
    // Log to watchdog.
    watchdog('cache bypass', 'Page cache was bypassed via user-agent string: %ua', array('%ua' => $_SERVER['HTTP_USER_AGENT']), WATCHDOG_NOTICE);

    // Reset the last poll time to now.
    variable_set('ua_cache_bypass_last_log', $time);
  }

  return;
}
